import { z } from 'zod';
import { GoogleGenAI, PersonGeneration } from '@google/genai';

const GenerateImageInputSchema = z.object({
  prompt: z.string().min(10).max(480).describe('Detailed visual description (max 480 tokens)'),
  numberOfImages: z.number().min(1).max(4).default(1).describe('Number of images to generate'),
  aspectRatio: z.enum(['1:1', '3:4', '4:3', '9:16', '16:9']).default('1:1').describe('Image aspect ratio'),
  apiKey: z.string().min(1).describe('User API key for Google AI')
});

export type GenerateImageInput = z.infer<typeof GenerateImageInputSchema>;

const GenerateImageOutputSchema = z.object({
  images: z.array(z.object({
    imageBytes: z.string().describe('Base64 encoded image data'),
    mimeType: z.string().describe('Image MIME type')
  })).describe('Generated images')
});

export type GenerateImageOutput = z.infer<typeof GenerateImageOutputSchema>;

export async function generateImage(input: GenerateImageInput): Promise<GenerateImageOutput> {
  const { prompt, numberOfImages, aspectRatio, apiKey } = input;

  try {
    // Initialize Google GenAI with the user's API key
    const ai = new GoogleGenAI({
      apiKey: apiKey
    });

    console.log('Generating image with Imagen model:', {
      promptLength: prompt.length, 
      numberOfImages,
      aspectRatio,
      hasApiKey: !!apiKey
    });

    // Use Imagen 4 model for high-quality image generation
    const response = await ai.models.generateImages({
      model: 'imagen-4.0-generate-preview-06-06',
      prompt: prompt,
      config: {
        numberOfImages: numberOfImages,
        aspectRatio: aspectRatio,
        personGeneration: PersonGeneration.ALLOW_ADULT // Allow generation of adults but not children
      },
    });

    if (!response.generatedImages || response.generatedImages.length === 0) {
      throw new Error('No images were generated by the model');
    }

    const images = response.generatedImages.map((generatedImage) => {
      if (!generatedImage.image?.imageBytes) {
        throw new Error('Invalid image data received from the model');
      }
      
      return {
        imageBytes: generatedImage.image.imageBytes,
        mimeType: generatedImage.image.mimeType || 'image/png'
      };
    });

    console.log(`Successfully generated ${images.length} image(s)`);
    return { images };

  } catch (error) {
    console.error('Image generation failed:', {
      error: error instanceof Error ? error.message : 'Unknown error',
      input: { promptLength: prompt.length, numberOfImages, aspectRatio }
    });
    
    // Provide more specific error messages based on common issues
    if (error instanceof Error) {
      if (error.message.includes('API key')) {
        throw new Error('Invalid API key. Please check your Google AI API key in settings.');
      } else if (error.message.includes('quota') || error.message.includes('limit')) {
        throw new Error('API quota exceeded. Please check your Google AI usage limits.');
      } else if (error.message.includes('region') || error.message.includes('location')) {
        throw new Error('Image generation is not available in your region.');
      } else if (error.message.includes('billing') || error.message.includes('payment')) {
        throw new Error('Image generation requires a paid Google AI account. Please upgrade your plan.');
      }
    }
    
    throw new Error(`Image generation failed: ${error instanceof Error ? error.message : 'Unknown error occurred'}`);
  }
}
