import { BaseAgent } from './base-agent';
import { genkit } from 'genkit';
import { googleAI } from '@genkit-ai/googleai';
import {
  AgentType,
  EventType,
  ActionType,
  Event,
  Action,
  ExecutionResult,
  Feedback,
  DecisionContext,
  AgentConfiguration
} from './types';

export class SalesPipelineAgent extends BaseAgent {
  protected async processEvents(events: Event[]): Promise<void> {
    console.log(`SalesPipelineAgent ${this.id} processing ${events.length} events`);
    
    for (const event of events) {
      if (event.type === EventType.DEAL_UPDATED) {
        this.context.conversationHistory.push({
          type: 'deal_updated',
          timestamp: event.timestamp,
          data: event.data
        });
      }
    }
  }

  protected async makeDecisions(context: DecisionContext): Promise<Action[]> {
    const actions: Action[] = [];
    
    for (const event of context.events) {
      if (event.type === EventType.DEAL_UPDATED) {
        const dealData = event.data;
        
        // Analyze deal progression
        const stageAnalysis = this.analyzeDealStage(dealData);
        const riskAssessment = this.assessDealRisk(dealData);
        
        // Update deal with AI insights
        actions.push({
          id: `analyze_deal_${event.id}_${Date.now()}`,
          type: ActionType.UPDATE_RECORD,
          agentId: this.id,
          timestamp: new Date(),
          parameters: {
            recordType: 'deal',
            recordId: dealData.dealId,
            dealData: dealData,
            stageAnalysis,
            riskAssessment,
            updates: {
              aiInsights: {
                stageAnalysis,
                riskAssessment,
                nextBestActions: [], // Will be generated by AI during execution
                lastAnalyzed: new Date()
              }
            }
          },
          priority: 6
        });

        // Create follow-up tasks if needed
        if (riskAssessment.risk === 'high') {
          actions.push({
            id: `risk_followup_${event.id}_${Date.now()}`,
            type: ActionType.CREATE_TASK,
            agentId: this.id,
            timestamp: new Date(),
            parameters: {
              taskType: 'deal_risk_mitigation',
              dealId: dealData.dealId,
              assignedTo: dealData.ownerId,
              priority: 'high',
              dueDate: new Date(Date.now() + 24 * 60 * 60 * 1000), // 24 hours
              description: `High-risk deal requires immediate attention: ${riskAssessment.reasons.join(', ')}`
            },
            priority: 8
          });
        }

        // Schedule follow-up if deal is stagnant
        if (stageAnalysis.daysInStage > 14) {
          actions.push({
            id: `stagnant_followup_${event.id}_${Date.now()}`,
            type: ActionType.SCHEDULE_FOLLOWUP,
            agentId: this.id,
            timestamp: new Date(),
            parameters: {
              dealId: dealData.dealId,
              followupType: 'stage_progression',
              scheduledFor: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000), // 2 days
              reason: `Deal has been in ${dealData.stage} stage for ${stageAnalysis.daysInStage} days`
            },
            priority: 5
          });
        }

        // Generate insights for forecasting
        if (dealData.stage === 'proposal' || dealData.stage === 'negotiation') {
          actions.push({
            id: `forecast_insight_${event.id}_${Date.now()}`,
            type: ActionType.GENERATE_INSIGHT,
            agentId: this.id,
            timestamp: new Date(),
            parameters: {
              insightType: 'deal_forecast',
              dealId: dealData.dealId,
              probability: this.calculateCloseProbability(dealData, stageAnalysis),
              expectedCloseDate: this.predictCloseDate(dealData, stageAnalysis),
              revenueImpact: dealData.value || 0
            },
            priority: 4
          });
        }
      }
    }

    return actions;
  }

  protected async executeActions(actions: Action[]): Promise<ExecutionResult[]> {
    const results: ExecutionResult[] = [];

    for (const action of actions) {
      try {
        let result: any = {};

        switch (action.type) {
          case ActionType.UPDATE_RECORD:
            result = await this.updateDealRecord(action.parameters);
            break;
          case ActionType.CREATE_TASK:
            result = await this.createTask(action.parameters);
            break;
          case ActionType.SCHEDULE_FOLLOWUP:
            result = await this.scheduleFollowup(action.parameters);
            break;
          case ActionType.GENERATE_INSIGHT:
            result = await this.generateInsight(action.parameters);
            break;
          default:
            throw new Error(`Unsupported action type: ${action.type}`);
        }

        results.push({
          actionId: action.id,
          success: true,
          result,
          timestamp: new Date()
        });
      } catch (error) {
        results.push({
          actionId: action.id,
          success: false,
          error: error instanceof Error ? error.message : String(error),
          timestamp: new Date()
        });
      }
    }

    return results;
  }

  protected async processFeedback(feedback: Feedback[]): Promise<void> {
    console.log(`SalesPipelineAgent ${this.id} processing ${feedback.length} feedback items`);
    
    for (const fb of feedback) {
      if (fb.outcome === 'success' && fb.score && fb.score > 0.8) {
        console.log(`High-performing sales action: ${fb.actionId}`);
      } else if (fb.outcome === 'failure') {
        console.log(`Failed sales action: ${fb.actionId} - ${fb.details}`);
      }
    }
  }

  private analyzeDealStage(dealData: any): {
    currentStage: string;
    daysInStage: number;
    stageHealth: 'healthy' | 'at_risk' | 'stagnant';
    progressScore: number;
  } {
    const stageOrder = ['lead', 'qualified', 'proposal', 'negotiation', 'closed_won', 'closed_lost'];
    const currentStageIndex = stageOrder.indexOf(dealData.stage);
    
    const daysInStage = dealData.stageUpdatedAt ? 
      Math.floor((Date.now() - new Date(dealData.stageUpdatedAt).getTime()) / (1000 * 60 * 60 * 24)) : 0;
    
    let stageHealth: 'healthy' | 'at_risk' | 'stagnant' = 'healthy';
    if (daysInStage > 21) stageHealth = 'stagnant';
    else if (daysInStage > 14) stageHealth = 'at_risk';
    
    const progressScore = Math.max(0, Math.min(100, 
      (currentStageIndex / (stageOrder.length - 2)) * 100 - (daysInStage * 2)
    ));

    return {
      currentStage: dealData.stage,
      daysInStage,
      stageHealth,
      progressScore
    };
  }

  private assessDealRisk(dealData: any): {
    risk: 'low' | 'medium' | 'high';
    score: number;
    reasons: string[];
  } {
    const reasons: string[] = [];
    let riskScore = 0;

    // Check for stagnation
    const daysInStage = dealData.stageUpdatedAt ? 
      Math.floor((Date.now() - new Date(dealData.stageUpdatedAt).getTime()) / (1000 * 60 * 60 * 24)) : 0;
    
    if (daysInStage > 21) {
      riskScore += 30;
      reasons.push('Deal stagnant for over 3 weeks');
    } else if (daysInStage > 14) {
      riskScore += 15;
      reasons.push('Deal stagnant for over 2 weeks');
    }

    // Check for lack of engagement
    if (!dealData.lastContactDate || 
        (Date.now() - new Date(dealData.lastContactDate).getTime()) > 7 * 24 * 60 * 60 * 1000) {
      riskScore += 25;
      reasons.push('No contact in over a week');
    }

    // Check for missing key information
    if (!dealData.decisionMaker) {
      riskScore += 20;
      reasons.push('Decision maker not identified');
    }

    if (!dealData.budget || dealData.budget === 0) {
      riskScore += 15;
      reasons.push('Budget not qualified');
    }

    // Check for competitive pressure
    if (dealData.competitors && dealData.competitors.length > 2) {
      riskScore += 10;
      reasons.push('High competitive pressure');
    }

    let risk: 'low' | 'medium' | 'high' = 'low';
    if (riskScore >= 50) risk = 'high';
    else if (riskScore >= 25) risk = 'medium';

    return { risk, score: riskScore, reasons };
  }

  private suggestNextActions(dealData: any, stageAnalysis: any): string[] {
    const actions: string[] = [];

    switch (dealData.stage) {
      case 'lead':
        actions.push('Qualify budget and timeline');
        actions.push('Identify decision makers');
        actions.push('Schedule discovery call');
        break;
      case 'qualified':
        actions.push('Conduct needs assessment');
        actions.push('Present solution overview');
        actions.push('Identify technical requirements');
        break;
      case 'proposal':
        actions.push('Follow up on proposal review');
        actions.push('Address any objections');
        actions.push('Schedule stakeholder meeting');
        break;
      case 'negotiation':
        actions.push('Finalize contract terms');
        actions.push('Get legal approval');
        actions.push('Prepare implementation plan');
        break;
    }

    if (stageAnalysis.stageHealth === 'at_risk') {
      actions.unshift('Urgent: Re-engage with prospect');
    }

    return actions;
  }

  private calculateCloseProbability(dealData: any, stageAnalysis: any): number {
    const stageProbabilities = {
      'lead': 10,
      'qualified': 25,
      'proposal': 50,
      'negotiation': 75,
      'closed_won': 100,
      'closed_lost': 0
    };

    let baseProbability = stageProbabilities[dealData.stage as keyof typeof stageProbabilities] || 0;
    
    // Adjust based on stage health
    if (stageAnalysis.stageHealth === 'stagnant') baseProbability *= 0.7;
    else if (stageAnalysis.stageHealth === 'at_risk') baseProbability *= 0.85;

    // Adjust based on engagement
    if (dealData.lastContactDate && 
        (Date.now() - new Date(dealData.lastContactDate).getTime()) < 3 * 24 * 60 * 60 * 1000) {
      baseProbability *= 1.1;
    }

    return Math.min(100, Math.max(0, Math.round(baseProbability)));
  }

  private predictCloseDate(dealData: any, stageAnalysis: any): Date {
    const averageStageDurations = {
      'lead': 7,
      'qualified': 14,
      'proposal': 21,
      'negotiation': 14
    };

    const currentStage = dealData.stage;
    const remainingDays = averageStageDurations[currentStage as keyof typeof averageStageDurations] || 30;
    
    // Adjust based on stage health
    let adjustedDays = remainingDays;
    if (stageAnalysis.stageHealth === 'stagnant') adjustedDays *= 1.5;
    else if (stageAnalysis.stageHealth === 'at_risk') adjustedDays *= 1.2;

    return new Date(Date.now() + adjustedDays * 24 * 60 * 60 * 1000);
  }

  private async updateDealRecord(parameters: any): Promise<any> {
    console.log(`Updating deal record ${parameters.recordId} with AI insights`);
    
    // Generate AI-powered next actions if deal data is available
    let nextBestActions: string[] = [];
    if (parameters.dealData && parameters.stageAnalysis) {
      nextBestActions = await this.generateAINextActions(
        parameters.dealData, 
        parameters.stageAnalysis, 
        parameters.riskAssessment
      );
    }

    // Update the insights with AI-generated actions
    if (parameters.updates.aiInsights) {
      parameters.updates.aiInsights.nextBestActions = nextBestActions;
    }

    return {
      recordId: parameters.recordId,
      recordType: parameters.recordType,
      updatedFields: Object.keys(parameters.updates),
      aiInsights: parameters.updates.aiInsights,
      timestamp: new Date()
    };
  }

  private async generateAINextActions(dealData: any, stageAnalysis: any, riskAssessment: any): Promise<string[]> {
    try {
      // Get API key from environment
      const apiKey = process.env.GEMINI_API_KEY;
      if (!apiKey) {
        console.warn('No API key available, falling back to predefined actions');
        return this.suggestNextActions(dealData, stageAnalysis);
      }

      // Create AI instance
      const userAI = genkit({
        plugins: [
          googleAI({ apiKey }),
        ],
      });

      const prompt = this.buildSalesInsightPrompt(dealData, stageAnalysis, riskAssessment);

      const response = await userAI.generate({
        model: googleAI.model('gemini-2.0-flash-exp'),
        prompt: prompt,
        config: {
          temperature: 0.3, // Lower temperature for more focused business advice
          maxOutputTokens: 800
        }
      });

      const aiResponse = response.text;
      
      // Parse the response to extract action items
      const actions = this.parseAIActionsResponse(aiResponse);
      
      return actions.length > 0 ? actions : this.suggestNextActions(dealData, stageAnalysis);

    } catch (error) {
      console.error('AI next actions generation failed:', error);
      // Fallback to predefined actions on error
      return this.suggestNextActions(dealData, stageAnalysis);
    }
  }

  private buildSalesInsightPrompt(dealData: any, stageAnalysis: any, riskAssessment: any): string {
    const currentTime = new Date().toLocaleString();
    
    return `You are a senior sales strategist and CRM expert with 15+ years of experience in B2B sales, deal management, and revenue optimization. You specialize in analyzing deal progression and providing actionable recommendations to accelerate sales cycles.

## Deal Analysis Context
**Analysis Time:** ${currentTime}
**Deal ID:** ${dealData.dealId || 'Unknown'}
**Deal Value:** $${dealData.value || 0}
**Current Stage:** ${dealData.stage || 'Unknown'}
**Days in Current Stage:** ${stageAnalysis.daysInStage || 0}
**Stage Health:** ${stageAnalysis.stageHealth || 'Unknown'}
**Progress Score:** ${stageAnalysis.progressScore || 0}/100

## Risk Assessment
**Risk Level:** ${riskAssessment.risk || 'Unknown'}
**Risk Score:** ${riskAssessment.score || 0}/100
**Risk Factors:** ${riskAssessment.reasons?.join(', ') || 'None identified'}

## Deal Details
**Company:** ${dealData.company || 'Not specified'}
**Decision Maker:** ${dealData.decisionMaker || 'Not identified'}
**Budget:** $${dealData.budget || 'Not qualified'}
**Timeline:** ${dealData.timeline || 'Not specified'}
**Last Contact:** ${dealData.lastContactDate || 'Unknown'}
**Competitors:** ${dealData.competitors?.join(', ') || 'None identified'}
**Deal Owner:** ${dealData.ownerId || 'Unassigned'}

## Your Mission
Analyze this deal comprehensively and provide 5-8 specific, actionable next steps that will:
1. Address the identified risk factors
2. Accelerate deal progression to the next stage
3. Increase the probability of closing
4. Mitigate competitive threats
5. Strengthen the relationship with key stakeholders

## Analysis Framework
Consider these critical sales factors:
- **Qualification Status**: BANT (Budget, Authority, Need, Timeline)
- **Stakeholder Mapping**: Decision makers, influencers, champions
- **Competitive Positioning**: Differentiation and value proposition
- **Objection Handling**: Anticipated concerns and responses
- **Relationship Strength**: Trust level and engagement quality
- **Process Alignment**: Their buying process vs. our sales process
- **Urgency Creation**: Business drivers and compelling events

## Action Prioritization
Prioritize actions based on:
1. **Impact on Close Probability** (High/Medium/Low)
2. **Urgency Based on Risk Level** (Immediate/This Week/This Month)
3. **Resource Requirements** (Low/Medium/High effort)
4. **Stage-Specific Effectiveness** (What works best at this stage)

## Response Format
Provide exactly 5-8 specific, actionable next steps in this format:

**IMMEDIATE ACTIONS (Next 24-48 hours):**
- [Specific action with clear outcome and timeline]

**THIS WEEK:**
- [Specific action with clear outcome and timeline]
- [Specific action with clear outcome and timeline]

**THIS MONTH:**
- [Specific action with clear outcome and timeline]
- [Specific action with clear outcome and timeline]

**STRATEGIC INITIATIVES:**
- [Longer-term action for deal advancement]
- [Longer-term action for relationship building]

## Quality Standards
Each action must be:
- **Specific**: Clear what to do, when, and with whom
- **Measurable**: Defined success criteria or outcome
- **Actionable**: Realistic and executable by the deal owner
- **Relevant**: Directly addresses deal progression or risk mitigation
- **Time-bound**: Clear timeline or deadline

Focus on high-impact activities that directly move this deal forward while addressing the identified risks and stage-specific challenges.`;
  }

  private parseAIActionsResponse(response: string): string[] {
    const actions: string[] = [];
    
    // Split response into lines and extract action items
    const lines = response.split('\n').filter(line => line.trim());
    
    for (const line of lines) {
      // Look for lines that start with bullet points or dashes
      if (line.match(/^[\s]*[-•*]\s+/) || line.match(/^\d+\.\s+/)) {
        const action = line.replace(/^[\s]*[-•*]\s+/, '').replace(/^\d+\.\s+/, '').trim();
        if (action.length > 10) { // Filter out very short items
          actions.push(action);
        }
      }
    }
    
    // If no bullet points found, try to extract sentences that look like actions
    if (actions.length === 0) {
      const sentences = response.split(/[.!?]+/).filter(s => s.trim().length > 20);
      for (const sentence of sentences.slice(0, 8)) { // Max 8 actions
        const trimmed = sentence.trim();
        if (trimmed.match(/^(schedule|contact|follow|send|prepare|review|identify|qualify|present|demo|propose|negotiate|close)/i)) {
          actions.push(trimmed);
        }
      }
    }
    
    // Ensure we have at least some actions, limit to 8 max
    return actions.slice(0, 8);
  }

  private async createTask(parameters: any): Promise<any> {
    console.log(`Creating ${parameters.taskType} task for deal ${parameters.dealId}`);
    return {
      taskId: `task_${Date.now()}`,
      dealId: parameters.dealId,
      taskType: parameters.taskType,
      assignedTo: parameters.assignedTo,
      priority: parameters.priority,
      dueDate: parameters.dueDate,
      timestamp: new Date()
    };
  }

  private async scheduleFollowup(parameters: any): Promise<any> {
    console.log(`Scheduling followup for deal ${parameters.dealId}`);
    return {
      followupId: `followup_${Date.now()}`,
      dealId: parameters.dealId,
      followupType: parameters.followupType,
      scheduledFor: parameters.scheduledFor,
      reason: parameters.reason,
      timestamp: new Date()
    };
  }

  private async generateInsight(parameters: any): Promise<any> {
    console.log(`Generating ${parameters.insightType} insight for deal ${parameters.dealId}`);
    return {
      insightId: `insight_${Date.now()}`,
      dealId: parameters.dealId,
      insightType: parameters.insightType,
      probability: parameters.probability,
      expectedCloseDate: parameters.expectedCloseDate,
      revenueImpact: parameters.revenueImpact,
      timestamp: new Date()
    };
  }
}

export function createSalesPipelineAgent(id: string): SalesPipelineAgent {
  const config: AgentConfiguration = {
    id,
    type: AgentType.SALES_PIPELINE,
    name: `Sales Pipeline Agent ${id}`,
    description: 'Manages deals and sales processes with AI insights',
    capabilities: [
      {
        name: 'Deal Analysis',
        description: 'Analyzes deal progression and identifies risks',
        requiredPermissions: ['read_deals', 'update_deals', 'create_tasks'],
        supportedEventTypes: [EventType.DEAL_UPDATED],
        supportedActionTypes: [
          ActionType.UPDATE_RECORD,
          ActionType.CREATE_TASK,
          ActionType.SCHEDULE_FOLLOWUP,
          ActionType.GENERATE_INSIGHT
        ]
      }
    ],
    enabled: true,
    priority: 6,
    maxConcurrentActions: 8,
    learningEnabled: true,
    configuration: {
      riskThreshold: 50,
      stagnationDays: 14,
      forecastingEnabled: true
    }
  };

  return new SalesPipelineAgent(config);
}